# Change these first
owner: kristianmsf # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: KMSF Host
    url: https://www.kmsfhost.com
    headers:
      User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64) AppleWebKit/537.36
    timeout: 10000
  - name: Kristianmsf
    url: https://www.kristianmsf.com
#  - name: IPv6 test
#    url: forwardemail.net
#    port: 80
#    check: "tcp-ping"
#    ipv6: true

workflowSchedule:
  upptime-updater: "*/5 * * * *"    # A cada 5 minutos
  update-templates: "0 0 * * *"    # Uma vez por dia

status-website:
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status KMSF
  introTitle: "Status dos serviços KMSF"
  introMessage: "Monitoramento de uptime dos nossos serviços. Tudo automatizado com GitHub Actions."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/kristianmsf/uptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
