# Change these first
owner: kristianmsf # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

actions:
  uptimeMonitor: v2
  
sites:
  - name: KMSFHost
    slug: kmsf-host
    url: https://www.kmsfhost.com
    type: globalping
    location: tokyo
    # O servidor está vivo mesmo com 403, pois responde
    # Alguns hosts bloqueiam GitHub Actions, então aceitamos 403 como "up"
    expectedStatusCodes:
      - 200
      - 403
      - 404
      
  - name: Kristianmsf
    slug: kristianmsf
    url: https://www.kristianmsf.com
    type: globalping
    location: tokyo
    # O servidor está vivo mesmo com 403, pois responde
    # Alguns hosts bloqueiam GitHub Actions, então aceitamos 403 como "up"
    expectedStatusCodes:
      - 200
      - 403
      - 404

#  - name: IPv6 test
#    url: forwardemail.net
#    port: 80
#    check: "tcp-ping"
#    ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status KMSF
  introTitle: "Status dos serviços KMSF"
  introMessage: "Monitoramento de uptime dos nossos serviços. Tudo automatizado com GitHub Actions."
  navbar:
    - title: Status
      href: /uptime
    - title: GitHub
      href: https://github.com/kristianmsf/uptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

workflowSchedule:
  upptime-updater: "*/5 * * * *"    # A cada 5 minutos
  update-templates: "0 0 * * *"    # Uma vez por dia
